### ISSUE TITLE
Format Bug

### ISSUE THREAD

**Issue by seggewiss** [MalteJanz/ludtwig#27]
I've created an example file, where {% endblock %} and {% block ... %} statements get parsed overeach other.
Run Ludtwig with the default configuration on a file with this content:

`{% block swag_amazon_pay_configuration_card_account %}
    <sw-card v-if="!showLoader"
             class="swag-amazon-pay-configuration"
             :title="$tc('swag-amazon-pay-configuration.configForm.cards.account')">

        {% block swag_amazon_pay_configuration_card_account_content %}
            {% block swag_amazon_pay_configuration_card_account_content_configuration_text %}

                <div class="swag-amazon-pay-configuration-text">
                    <span class="headline headline-m">{{ $tc('swag-amazon-pay-configuration.configForm.registerHeadline') }}</span>
                    <span v-html="$tc('swag-amazon-pay-configuration.configForm.registerExplanation')"></span>
                </div>
                <div class="swag-amazon-pay-configuration-text">
                    <span class="headline headline-m">{{ $tc('swag-amazon-pay-configuration.configForm.existingAccountHeadline') }}</span>
                    <span v-html="$tc('swag-amazon-pay-configuration.configForm.existingAccountExplanation')"></span>
                </div>
            {% endblock %}

            {% block swag_amazon_pay_configuration_card_account_content_headline_account_information %}
                <div class="swag-amazon-pay-configuration-text add-margin-top">
                            <span class="headline headline-s">
                                {{ $tc('swag-amazon-pay-configuration.configForm.accountHeadline') }}
                            </span>
                </div>
            {% endblock %}

            {% block swag_amazon_pay_configuration_card_account_content_option_ledger_currency %}
                <div class="sw-field--margin-top">
                    <sw-single-select
                            v-model="config.ledgerCurrency"
                            required
                            :options="getLedgerCurrencyOptions"
                            :label="$tc('swag-amazon-pay-configuration.configForm.fields.ledgerCurrency.label')"
                            :placeholder="$tc('swag-amazon-pay-configuration.configForm.fields.ledgerCurrency.placeholder')"
                            :disabled="isInherited">
                    </sw-single-select>
                </div>
            {% endblock %}

            <div class="swag-amazon-pay-configuration-columns">
                <div class="column">

                    {% block swag_amazon_pay_configuration_card_account_content_option_merchant_id %}
                        <sw-text-field
                                v-model="config.merchantId"
                                required
                                :label="$tc('swag-amazon-pay-configuration.configForm.fields.merchantId.label')"
                                :placeholder="$tc('swag-amazon-pay-configuration.configForm.fields.merchantId.placeholder')"
                                :disabled="isInherited">
                        </sw-text-field>
                    {% endblock %}

                </div>
                <div class="column"></div>
                <div class="column">

                    {% block swag_amazon_pay_configuration_card_account_content_option_client_id %}
                        <sw-text-field
                                v-model="config.clientId"
                                required
                                :label="$tc('swag-amazon-pay-configuration.configForm.fields.clientId.label')"
                                :placeholder="$tc('swag-amazon-pay-configuration.configForm.fields.clientId.placeholder')"
                                :disabled="isInherited">
                        </sw-text-field>
                    {% endblock %}

                </div>
            </div>

            {% block swag_amazon_pay_configuration_card_account_content_headline_credentials %}
                <div class="swag-amazon-pay-configuration-text add-margin-top">
                            <span class="headline headline-s">
                                {{ $tc('swag-amazon-pay-configuration.configForm.credentialsHeadline') }}
                            </span>
                </div>
            {% endblock %}

            {% block swag_amazon_pay_configuration_card_account_content_option_public_key_id %}
                <sw-text-field
                        v-model="config.publicKeyId"
                        required
                        :label="$tc('swag-amazon-pay-configuration.configForm.fields.publicKeyId.label')"
                        :placeholder="$tc('swag-amazon-pay-configuration.configForm.fields.publicKeyId.placeholder')"
                        :disabled="isInherited">
                </sw-text-field>
            {% endblock %}

            {% block swag_amazon_pay_settings_card_account_private_key_modal %}
                <swag-amazon-pay-configuration-input-key-modal
                        v-if="showInputKeyModal"
                        @update-private-key="onUpdatePrivateKey"
                        @modal-close="onCloseModal()">
                </swag-amazon-pay-configuration-input-key-modal>
            {% endblock %}

            {% block swag_amazon_pay_configuration_card_account_content_field_private_key %}
                <sw-password-field
                        :placeholder="getPrivateKeyPlaceholder()"
                        :label="$tc('swag-amazon-pay-configuration.configForm.fields.privateKey.label')"
                        required
                        disabled
                        :passwordToggleAble="false">
                </sw-password-field>
            {% endblock %}

            {% block swag_amazon_pay_configuration_card_account_content_button_input_private_key %}
                <sw-button
                        variant="primary"
                        :disabled="isInherited"
                        @click="displayInputKeyModal">
                    {{ $tc('swag-amazon-pay-configuration.actions.insertPrivateKey') }}
                </sw-button>
            {% endblock %}

            {% block swag_amazon_pay_configuration_card_account_content_config_test %}
                <sw-button-process
                        v-if="!showLoader"
                        class="sw-settings-login-registration__test-action"
                        :isLoading="showLoader"
                        :processSuccess="isTestSuccessful"
                        :disabled="showLoader || isTesting || isInherited"
                        @click="onTest">
                    {{ $tc('swag-amazon-pay-configuration.actions.testConnection') }}
                </sw-button-process>
            {% endblock %}
        {% endblock %}

    </sw-card>
{% endblock %}`

The blocks inside swag_amazon_pay_configuration_card_account_content  get rendered under each other without the blank lines. Eventhough the blank lines are there before parsing it.

**Comment by MalteJanz** [comment]
Thanks for the bug report :)
It looks like that i didn't catch this case when printing newlines. There is one exception to printing a new line before / after a block:
if there are blocks directly nested inside each other.

But this obviously should not apply here. Basicly it should prevent thinks like these
```twig
{% block a %}

    {% block b %}
        
        {% block c %}
            {# deprecated ... #}
        {% endblock %}

    {% endblock %}

{% endblock %}
```
So they look like these:
```twig
{% block a %}
    {% block b %}
        {% block c %}
            {# deprecated ... #}
        {% endblock %}
    {% endblock %}
{% endblock %}
```

The solution would be to only skip the newlines if there is no more than 1 children for the block and the child itself is also a block.

A other solution would be to simplify the newline logic around blocks and enforce them always which would leed to the above example of not very helpfull newlines.

**Comment by MalteJanz** [comment]
@seggewiss Have a look at this MR:  https://github.com/MalteJanz/ludtwig/pull/28

Does the newly formatted output match your expectations? Or have you another suggestion how the output should look like?

If you are fine with that i would merge it and do another release (because this bug looks kind of anoying). The good thing is: the logic for this is now refactored and a little bit more readable (i still don't quite like it but don't know how to handle it cleaner) and there is another automated test case for this.

**Comment by seggewiss** [comment]
Already gave your MR a :+1:.
