### ISSUE TITLE
Rule "twig-block-name-snake-case" applies for numbers within string

### ISSUE THREAD

**Issue by tobiasberge** [MalteJanz/ludtwig#48]
The rule `twig-block-name-snake-case` applies for numbers directly within a string. I guess it assumes `page_product_detail_rich_snippets_gtin_13` instead.

```
   ┌─ storefront/page/product-detail/buy-widget.html.twig:12:22
   │
12 │             {% block page_product_detail_rich_snippets_gtin13 %}
   │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: rename this block in snake_case
```

```
   ┌─ storefront/page/account/register/index.html.twig:28:54
   │
28 │                                             {% block page_account_register_advantages_entry1 %}
   │                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: rename this block in snake_case
```

Examples:
```twig
{# storefront/page/account/register/index.html.twig #}

{% block page_account_register_advantages_entry1 %}
{% block page_account_register_advantages_entry2 %}
{% block page_account_register_advantages_entry3 %}
{% block page_account_register_advantages_entry4 %}
```

I kind of agree with the rule that it would be prettier to have a `_` before the number. However, for shopware [platform](https://github.com/shopware/platform) (Storefront) we would have to do deprecations and "unnecessary" major version changes in order to fix it. What do you think? Should this be configurable or allowed?

There can be also stuff like "proper names" `{% block b2b_something %}` where `b_2_b_something` might be overkill and look strange.

I think for the time being we can ignore those blocks in platform.

**Comment by MalteJanz** [comment]
### The main issue
For me things like:
```twig
{% block page_account_register_advantages_entry1 %}
{% block page_account_register_advantages_entry2 %}

{% block b2b_something %}

{% block something_v1_child %}
```
should all stay the same and don't get suggestions for splitting the number apart.

Only obvious non `snake_case` names should be reported and suggested (the above are in my view still valid `snake_case`).

But cases like:
```twig
{% block pageAccountRegister %}
{% block page-account-register %}

{% block b2bSomething %}

{% block something_v1-child %}
```
should be reported and ideally would also have a suggestion.

### The other issue
You mention that this causes breaking changes in Shopware. I would suggest using `{# ludtwig-ignore twig-block-name-snake-case #}` for these places then.

#### The maybe issue
`--fix` maybe fixes too much 🤷‍♂️ . We could add some kind of filtering / levels to the suggestions (like `Styling`, `Naming`, `Refactoring` or something with a more obvious order 🤔 ) and then run `--fix styling`, which only fixes stylistic issues like indentation and line breaks. But that requires quite a bit of extra work and I don't think it is worth it at this point (feel free to prove me wrong).
