### ISSUE TITLE
Confusion around `unknown-token` rule output

### ISSUE THREAD

**Issue by mitelg** [MalteJanz/ludtwig#88]
> note[unknown-token]: Unknown syntax token found

The third `li` contains unknown syntax

```html
<div class="cms-section">
    <ol>
        <li>Test List</li>
        <li>Pay Later</li>
        <li>New „Payment Upon Invoice“ (Germany)</li>
        <li>Seamless checkout experience</li>
        <li>Easy integration into your Shopware shop</li>
    </ol>
</div>
```

**Comment by MalteJanz** [comment]
FYI: The rule `unknown-token` is not necessary most of the time (can be removed from `ludtwig-config.toml`). It was created in the beginning of the project to check that the lexer can lex the whole template.

It just reports unknown tokens (which aren't defined in the parser / don't have any meaning).

I guess I can also remove this rule if it only causes confusion 🙈
